version: '3.9'

services:
  mongodb:
    image: mongo:7.0
    ports:
      - 27017:27017
    environment:
      - MONGO_INITBD_ROOT_USERNAME=root
      - MONGO_INITBD_ROOT_PASSWORD=root123
    volumes:
      - ./mongo_data:/data/db
